<p><img alt="Colaboratory logo" height="140px" src="https://upload.wikimedia.org/wikipedia/commons/archive/f/fb/20161010213812%21Escudo-UdeA.svg" align="left" hspace="10px" vspace="0px"></p>

# **Fundamentos de programación**


El presente curso hace parte de la especialización de analítica y ciencia de datos de la facultad de Ingeniería de la Universidad de Antioquia.

## **Sesión 1**

## **Contenido**
  
- <a href="#num"> NumPy</a><br>
- <a href="#arr"> Arreglos en NumPy</a><br>
- <a href="#ope"> Operaciones sobre los arreglos</a><br>
- <a href="#apeA"> Apéndice A: Iteradores útiles</a><br>



La implementación estándar de Python está escrita en C. Esto significa que cada objeto de Python es simplemente una estructura de C, que contiene no solo su valor, sino también otra información. Ya hemos visto que cuando definimos una variable, esta es en realidad un puntero a una estructura compuesta de C, que contiene ciertos valores diferentes: referencia, tipo, tamaño, valor, etc.

![variables in C](https://i.imgur.com/0RQOTQ0.png)

![](https://i.imgur.com/F3IQqwE.png)

Recordemos que en Python, al ser un lenguaje de tipado dinámico, podemos generar listas donde cada uno de sus elementos pueden ser de cualquier tipo

In [ ]:
L = [True, "2", 3.0, 4]

[type(i) for i in L]

[bool, str, float, int]

Esta flexibilidad tiene un costo: cada elemento de la lista debe contener su propia información, es decir, cada elemento es un objeto completo de Python. En el caso especial en que todas las variables sean del mismo tipo, gran parte de esta información es redundante: puede ser mucho más eficiente almacenar datos en una lista de tipo homogéneo. Python ofrece diferentes opciones para almacenar datos de esta manera (por ejemplo a través del módulo `array`). Sin embargo, la mejor manera de generar este tipo de objetos es a través de la libreria NumPy.



<p><a name="num"></a></p>

## **NumPy** (Numerical Python)

En el núcleo de la mayoría de los problemas encontramos un **arreglo**. Desde el punto de vista computacional, un arreglo es un bloque contiguo de memoria donde cada elemento tiene el mismo tipo.

Los diferentes lenguajes de programación utilizados en computación científica tienen alguna noción de manejo de datos basado en arreglos, ya sea integrado en el lenguaje propio o a través de paquetes proporcionados por terceros.

NumPy es el paquete fundamental para la computación científica en Python. Es una libreria de Python que proporciona herramientas para la generación de arreglos y una variedad de funcionalidades para realizar operaciones sobre estos, que generalmente se realizan de una manera más eficiente que lo que se puede lograr con funcionalidades propias de Python. NumPy sirve como bloque básico para una gran cantidad de paquetes científicos y de análisis de datos.

En el núcleo de NumPy, está el objeto `ndarray` (n-dimensional array). Este encapsula arreglos n-dimensionales de tipos de datos homogéneos, con muchas operaciones que se realizan en código compilado, con lo cual se mejora el rendimiento significativamente. La diferencia entre una lista de tipo dinámico y un arreglo de tipo fijo (al estilo NumPy) se ilustra en la siguiente figura:



<p><img alt="Colaboratory logo" height="350px" src="https://i.imgur.com/8EbyB0c.png" align="left" hspace="10px" vspace="0px"></p>

Al nivel de implementación, el arreglo contiene esencialmente un puntero único a un bloque contiguo de datos. La lista de Python, por otro lado, contiene un puntero a un bloque de punteros, cada uno de los cuales a su vez apunta a un objeto completo de Python como el entero de Python que vimos anteriormente.

En resumen, estas son las diferencias más importantes entre los arreglos de NumPy y las secuencias estándar de Python:

* Todos los elementos en un arreglo de NumPy deben ser del mismo tipo de dato y, por lo tanto, tendrán el mismo tamaño en memoria.
* Los arreglos de NumPy tienen un tamaño fijo en la creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). Cambiar el tamaño de un `ndarray` creará un nuevo arreglo y eliminará el original.
* Los arreglos de NumPy facilitan operaciones avanzadas matemáticas y de otro tipo en grandes cantidades de datos. Típicamente, tales operaciones se ejecutan de manera más eficiente que usando las secuencias integradas de Python.



<p><a name="arr"></a></p>

# **Arreglos en Numpy**

Por convención, la librería NumPy se import con el alias `np`

In [ ]:
# from numpy import *
# from numpy import array

In [ ]:
import numpy as np


Podemos construir un objeto `ndarray`, a partir de una lista de Python, mediante el constructor `array`:


In [ ]:
arreglo =  np.array( [1, 2, 3])

In [ ]:
print(arreglo)

[1 2 3]


In [ ]:
type(arreglo)

numpy.ndarray

El objeto `ndarray` representa efectivamente un bloque de memoria de tamaño fijo, el cual contiene una serie de atributos y métodos que definen su estructura. Veamos algunos de los atributos más importantes de este objeto:

### **dtype:**

El tipo de dato (data type) es el atributo más importante. Este determina el tamaño y el significado de cada elemento del arreglo. El sistema predeterminado de dtypes que proporciona NumPy (ver siguiente imagen) es más preciso y más amplio para los tipos básicos que el sistema de tipos que implementa el lenguaje Python. Podemos ver el data type como `arreglo.dtype`

In [ ]:
arreglo.dtype

dtype('int64')

<p><img alt="Colaboratory logo" height="400px" src="https://i.imgur.com/2RpU9w1.png" align="left" hspace="10px" vspace="0px"></p>

In [ ]:
arreglo =  np.array( [1, 2, 3], dtype= 'float16')
print(arreglo)
arreglo.dtype

[1. 2. 3.]


dtype('float16')

### **shape:**

Atributo que devuelve una tupla de enteros que representa el rango a lo largo de cada dimensión de los arreglos n-dimensionales.

In [ ]:
l = [[1,2], [3,4]]
arr2 = np.array(l)
arr = np.array([1, 2, 3, 4])
arr.shape

(4,)

La forma `(4,)`, nos dice que `l` es un arreglo unidimensional, donde la dimensión tiene un rango 4. La dimensión y el número de elementos del arreglo se pueden obtener mediante los atributos `ndim` y `size`, respectivamente:

In [ ]:
arr.ndim

1

In [ ]:
arr2.size

4

In [ ]:
len(arr2)

2

Podemos modificar la forma del arreglo modificando el atributo shape:

In [ ]:
arr2.shape = (2,2)
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
arr2.shape

(2, 2)

Alternativamente, NumPy proporciona el método `reshape`, con el cual podemos cambiar la forma de un arreglo. Este toma como argumento el arreglo a modificar y un entero o tupla que represente la nueva forma.

Esta nueva forma debe ser compatible con el número de elementos que tenga el arreglo. Cambiemos la forma de `l` para tener un vector fila:

In [ ]:
np.array([i for i in range(1,7)]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

NumPy nos permite pasar una de las dimensiones como `-1`. De esta manera, Numpy se encargará de que el rango en esa dimensión sea compatible con el arreglo original y con el rango de la dimensión que se fijó:

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.reshape(1,-1)

array([[1, 2, 3, 4]])

In [ ]:
arr.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4]])

## **Formas alternativas de construir arreglos:**

NumPy proporciona formas alternativas de crear arreglos. Las funciones más comunes son `arange`, `linspace` `zeros`, `ones`, `full` y `empty`.

####**Tarea**

Consultar cómo construir arreglos con números aleatorios. ¿Se puede construir un arreglo con números aleatorios que sigan una distribución normal, exponencial?

* La función `arange()` toma un inicio, final y un paso como la función `range()` de Python, excepto que devuelve un `ndarray` y que el paso puede ser un número real.

In [ ]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

- La función `linspace` crea una serie de puntos uniformemente entre un límite inferior y superior que incluye ambos extremos. Su sintáxis es de la forma:

>
    linspace(inicio, final, numero de puntos)

In [ ]:
a = np.linspace(0.5,10.5,100, endpoint= False)
a

array([ 0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,
        2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,
        3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,
        4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,
        6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ,
        7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,
        8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,  9.2,
        9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1, 10.2, 10.3,
       10.4])

In [ ]:
np.linspace(0.5,10.5,100, retstep= True)

(array([ 0.5       ,  0.6010101 ,  0.7020202 ,  0.8030303 ,  0.9040404 ,
         1.00505051,  1.10606061,  1.20707071,  1.30808081,  1.40909091,
         1.51010101,  1.61111111,  1.71212121,  1.81313131,  1.91414141,
         2.01515152,  2.11616162,  2.21717172,  2.31818182,  2.41919192,
         2.52020202,  2.62121212,  2.72222222,  2.82323232,  2.92424242,
         3.02525253,  3.12626263,  3.22727273,  3.32828283,  3.42929293,
         3.53030303,  3.63131313,  3.73232323,  3.83333333,  3.93434343,
         4.03535354,  4.13636364,  4.23737374,  4.33838384,  4.43939394,
         4.54040404,  4.64141414,  4.74242424,  4.84343434,  4.94444444,
         5.04545455,  5.14646465,  5.24747475,  5.34848485,  5.44949495,
         5.55050505,  5.65151515,  5.75252525,  5.85353535,  5.95454545,
         6.05555556,  6.15656566,  6.25757576,  6.35858586,  6.45959596,
         6.56060606,  6.66161616,  6.76262626,  6.86363636,  6.96464646,
         7.06565657,  7.16666667,  7.26767677,  7.3

- Las funciones `zeros()` y `ones()` toman un entero o una tupla de enteros como argumento y devuelven un `ndarray` cuya forma coincide con la de la tupla y cuyos elementos son cero o uno:

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- La función `full()` funciona de manera similar a `zeros()` y `ones()`, solo que podemos llenar el arreglo con cualquier valor:

In [ ]:
np.full((3,4), 17.5)

array([[17.5, 17.5, 17.5, 17.5],
       [17.5, 17.5, 17.5, 17.5],
       [17.5, 17.5, 17.5, 17.5]])

- La función `empty()`, por otro lado, asignará memoria sin asignarle ningún valor. Esto significa que el contenido de un arreglo vacío será lo que esté en la memoria en ese momento. Esto es particularmente útil cuando creamos un arreglo cuyos valores serán modificados posteriormente.

In [ ]:
pi = 3.14
e = 2.7
r =17.2
np.empty((5,4))

array([[4.67486566e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

<p><a name="ope"></a></p>

# **Operaciones sobre los arreglos**

Ahora que hemos visto cómo definir arreglos de NumPy, podemos discutir cómo realizar operaciones sobre los arreglos. La clave para hacer estas operaciones de una forma rápida y eficiente es usar operaciones **vectorizadas**, implementadas a través de las funciones universales de NumPy (ufuncs).

Recordemos que la operación de sumar dos listas de Python resulta en la concatenación de dichas listas:



In [ ]:
lista1 = [ 1, 2, 3, 4]
lista2 = [5, 6 ,7 , 8]

lista1 + lista2

[1, 2, 3, 4, 5, 6, 7, 8]

Si quisieramos sumar elemento a elemento, debemos hacer explícito un ciclo `for` con la función `zip()` para dos variables de la siguiente manera (ver **Apéndice A**):

In [ ]:
#forma 1

for i in range(len(lista1)):
  print(lista1[i] + lista2[i])

6
8
10
12


In [ ]:
for i,j in zip(lista1, lista2):
  print(i + j)

6
8
10
12


In [ ]:
arreglo_1 = np.array(lista1)
arreglo_2 = np.array(lista2)

arreglo_1 + arreglo_2

array([ 6,  8, 10, 12])

Si realizamos esta misma operación con arreglos de Numpy, obtendremos otra salida:

In [ ]:
np.add(lista1, lista2)

array([ 6,  8, 10, 12])

In [ ]:
np.add(arreglo_1, arreglo_2)

array([ 6,  8, 10, 12])

Como los arreglos son de NumPy, se está realizando lo que se conoce como una operación **vectorizada**, la cual es una operación sobre los arreglos que se realiza **elemento a elemento**, mediante lo que conocemos como funciones universales (ufuncs) de Numpy.

Las ufuncs de NumPy se sienten muy naturales de usar porque hacen uso de los operadores aritméticos nativos de Python.

La siguiente tabla nos muestra algunas de las funciones universales disponibles en Numpy (ver [documentación](https://numpy.org/doc/stable/reference/ufuncs.html#ufunc))







![picture](https://i.imgur.com/8HaZzxg.png)

Note que estas se muestran en dos versiones: mediante un operador y su correspondiente función universal. Por ejemplo `+` y `np.add`. Como en el ejemplo anterior, si los arreglos son de NumPy, el operador que utilicemos para realizar las operaciones representará la función universal. Si el arreglo no se define como uno de NumPy, y si queremos aplicar una función universal, debemos utilizar la forma explícita de la función universal

En el caso de la multiplicacion en Python, la multiplicación de un número entero $n$ por una lista $l$, nos arroja una lista que contiene los elementos de $l$ $n$ veces:



In [ ]:
n = 3

lista1 * n

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

Si quisieramos multiplicar el entero por cada uno de los elementos de la lista $l$ debemos incluir un ciclo for:

In [ ]:
[n * elemento for elemento in lista1]

[3, 6, 9, 12]

Además, la operación de multiplicación entre listas no está definida:

In [ ]:
try:
  lista1 * lista2
except Exception as e:
  print(e)

can't multiply sequence by non-int of type 'list'


En NumPy, ambas operaciones se hacen de forma vectorizada:

In [ ]:
n * arreglo_1

array([ 3,  6,  9, 12])

In [ ]:
np.multiply(n, lista1)

array([ 3,  6,  9, 12])

Note que ambas operaciones se hacen elemento a elemento, caracteriztica de las operaciones vectorizadas implementadas a través de ufuncs. Note además, que en el caso de la multiplicación de arreglos, la salida no corresponde a lo que conocemos como producto punto. Para realizar esta operación, tanto en arreglos unidimensionales como n-dimensionales, podemos utilizar la función universal `np.dot` o su operador asociado `@`:

In [ ]:
arreglo_1 * arreglo_2

array([ 5, 12, 21, 32])

In [ ]:
np.dot(arreglo_1 , arreglo_1)

30

In [ ]:
arreglo_1 @ arreglo_1

30

Es importante mencionar que el uso de operaciones vectorizadas no solo significa la utilización de funciones universales para la realización de las operaciones elemento a elemento.

En el contexto de lenguajes de alto nivel como Python, el término **vectorización** representa el uso de código optimizado y precompilado escrito en lenguajes de bajo nivel (por ejemplo C) para realizar operaciones matemáticas en una secuencia de datos. Esto se realiza en lugar de una iteración explicita escrita en código nativo, como ya vimos en el ejemplo de la multiplicacion, que hace que las operaciones sean más eficientes.

**Ejercicio**

Veamos un ejemplo con el cual se ilustra la eficiencia computacional que se alcanza con las operaciones vectorizadas de NumPy: Construyamos una función que calcule el recíproco de una lista

In [ ]:
def Lista_Reciprocos(lista):
  """
  Esta función calcula una lista con los recíprocos
  de los elemntos de la lista que acepta por entrada
  """
  salida = []
  for elemento in lista:
    salida.append(1/elemento)

  return salida

Lista_Reciprocos([1, 2, 3])

[1.0, 0.5, 0.3333333333333333]

In [ ]:
a = list(range(1,100000))

In [ ]:
%timeit Lista_Reciprocos(a)

100 loops, best of 5: 10.8 ms per loop


La operación equivalente en NumPy, utilizando ufuncs, será:

In [ ]:
R = np.arange(1,100000)

In [ ]:
%timeit 1/R

The slowest run took 13.13 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 199 µs per loop


Note que hay tres ordenes de magnitud de diferencia en el tiempo de computo en ambas versiones.

Resulta que el cuello de botella aquí no son las operaciones en sí mismas, sino la verificación de tipos y demás que Python debe hacer en cada ciclo. Cada vez que se calcula el recíproco, Python primero examina el tipo de objeto y realiza una búsqueda dinámica de la función correcta que se utilizará para ese tipo. Si estuviéramos trabajando en código compilado, esta especificación de tipo se conocería antes de que se ejecute el código y el resultado podría calcularse de manera mucho más eficiente.

Los cálculos que usan vectorización a través de ufuncs son casi siempre más eficientes que su contraparte implementada a través de ciclos, especialmente a medida que los arreglos crecen en tamaño. Cada vez que se vea un ciclo de este tipo en Python, debe considerarse si este puede reemplazarse con una expresión vectorizada.

**Ejercicio:**  La serie de Leibniz  $$\frac{\pi}{4}=1-\frac{1}{3}+\frac{1}{5}-\frac{1}{7} -\frac{1}{9}+ \cdot \cdot \cdot=\sum_{n=0}^{\infty} \frac{(-1)^n}{2n+1}$$ La serie de Leibniz permite obtener un valor aproximado para el número $\pi$. Escriba un programa en el que dado el número de términos de la sumatoria, se calcule y muestre el valor aproximado de $\pi$.

 $$\pi=4\sum_{n=0}^{\infty} \frac{(-1)^n}{2n+1}$$

$$\sum_{n = 1}^{i} n$$

In [ ]:
import time


lista=[]
valor=int(input("Ingrese valor y (0 para finalizar):"))
while valor!=0:
    lista.append(valor)
    valor=int(input("Ingresar valor (0 para finalizar):"))
lista2=[]
t = time.clock()
for i in range (len(lista)):
  lista2.append(1/lista[i])
print (lista2)
t2 = time.clock()- t
print(t2)

Ingrese valor y (0 para finalizar):1
Ingresar valor (0 para finalizar):2
Ingresar valor (0 para finalizar):3
Ingresar valor (0 para finalizar):4
Ingresar valor (0 para finalizar):0
[1.0, 0.5, 0.3333333333333333, 0.25]
0.00042400000000242244


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


In [ ]:
def suma(n):
  return sum(i for i in range(1,n+1))

suma(100)

5050

In [ ]:
def leib(n):
  return 4*sum(((-1)**i)/(2*i+1) for i in range(0,n))

leib(100000)

3.1415826535897198

In [ ]:
def Py_numpy(m):
  n = np.arange(m+1)
  return 4 * np.sum((-1)**n/(2*n + 1))
Py_numpy(100000)

3.1416026534897927

In [ ]:
%timeit leib(100000)

10 loops, best of 5: 39.7 ms per loop


In [ ]:
%timeit Py_numpy(100000)

100 loops, best of 5: 6.81 ms per loop


<p><a name="apeA"></a></p>

# **Apéndice A: Iteradores útiles**

A menudo vamos a necesitar iterar los diferentes objetos de diversas formas, por lo que vamos a requerir de iteradores que nos permitan tener más libertad a la hora de definir las iteracions. Veamos algunos de estos iteradores disponibles en Python.

Por ejemplo, si quisieramos iterar sobre una lista de manera que la variable de iteración corra de forma ordenada sobre los elementos, es decir, no sobre los elementos de acuerdo a su posición en la lista sino de acuerdo a su valor numérico, podemos utilizar el método `sorted` sobre la lista:

In [ ]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]

In [ ]:
print(list(zip(l1,l2)))

[(1, 5), (2, 6), (3, 7), (4, 8)]


In [ ]:
for i, j in zip(l1, l2):
  print(i ,j)

1 5
2 6
3 7
4 8


In [ ]:
for i in range(1, 5):
  for j in range(5, 9):
    print( i+ j)

6
7
8
9
7
8
9
10
8
9
10
11
9
10
11
12


In [ ]:
L = [5, 2, 7, 1]

for i in sorted(L):
  print(i)

1
2
5
7


Ahora, supongamos que necesitamos iterar sobre los elementos de una lista y además tener registro del índice del elemento. Podríamos escribir algo como:


In [ ]:
L = range(4,8)

for i in range(len(L)):
  print(f"indice: {i} valor: {L[i]}")

indice: 0 valor: 4
indice: 1 valor: 5
indice: 2 valor: 6
indice: 3 valor: 7


Podemos realizar esta iteración utilizando el iterador `enumerate`, que produce un generador de tuplas con los índices y valores de la lista:

In [ ]:
list(enumerate(L))

[(0, True), (1, '2'), (2, 3.0), (3, 4)]

In [ ]:
for i, valor in enumerate(L):
  print(f"indice: {i} valor: {valor}")

indice: 0 valor: True
indice: 1 valor: 2
indice: 2 valor: 3.0
indice: 3 valor: 4


En otras ocaciones, vamos a querer iterar sobre varias listas simultáneamente. Una forma directa de hacerlo sería iterando sobre el índice de las listas


In [ ]:
l = range(2,4)
r = range(6,8)

for i in range(len(l)):
  print(f"l_val: {l[i]}, r_val: {r[i]}")

l_val: 2, r_val: 6
l_val: 3, r_val: 7


Si, por ejemplo, cambiaramos la longitud de `l`, obtendríamos un error

In [ ]:
l = range(2,5)
r = range(6,8)

for i in range(len(l)):
  print(f"l_val: {l[i]}, r_val: {r[i]}")

l_val: 2, r_val: 6
l_val: 3, r_val: 7


IndexError: ignored

esta iteración se puede llevar a cabo mediante el iterador `zip`, que permite iterar sobre varios objetos iterables simultáneamente:

In [ ]:
type(range(10))

range

In [ ]:
list(zip(l, r))

[(2, 6), (3, 7)]

In [ ]:
for lval, rval in zip(l, r):
  print(f"l_val: {lval}, r_val: {rval}")

l_val: 2, r_val: 6
l_val: 3, r_val: 7


`zip` produce un generador de tuplas obtenidas a partir de los objetos iterables que pasemos como argumento. Tenga en cuenta que el iterador admite diferentes objetos para la iteración

In [ ]:
for i,j in zip(range(3), "abc"):
  print(i,j)

0 a
1 b
2 c


así como objetos de tamaños diferentes

In [ ]:
for i,j,k in zip((1,2,3), "abc", [4,5,6,7]):
  print(i,j,k)

Note que las tuplas se producen con una longitud tal que coincida con el número de elementos del objeto de menor longitud.